from __future__ import annotations

import struct
import subprocess
from pathlib import Path
from typing import Iterable

from .common import require_dir, require_file
from .config import SFUZZ_HOME


DEFAULT_SMOKE_HEX = "73001000"


def parse_hex_blob(text: str) -> bytes:
    cleaned = text.strip().replace("_", "").replace(" ", "")
    if cleaned.startswith(("0x", "0X")):
        cleaned = cleaned[2:]
    if len(cleaned) % 2:
        raise ValueError(f"hex payload must contain an even number of digits: {text!r}")
    return bytes.fromhex(cleaned)


def read_seed_metadata_name(seed: Path) -> str:
    try:
        data = seed.read_bytes()
        cursor = 0

        def take(size: int) -> bytes:
            nonlocal cursor
            if cursor + size > len(data):
                raise ValueError("short SFUZ file")
            chunk = data[cursor : cursor + size]
            cursor += size
            return chunk

        def u16() -> int:
            return struct.unpack("<H", take(2))[0]

        def u32() -> int:
            return struct.unpack("<I", take(4))[0]

        def skip_blob() -> None:
            nonlocal cursor
            size = u32()
            if cursor + size > len(data):
                raise ValueError("blob exceeds file size")
            cursor += size

        def read_string() -> str:
            size = u32()
            raw = take(size)
            return raw.decode("utf-8", errors="replace")

        if take(4) != b"SFUZ":
            return seed.stem
        version = u16()
        _flags = u16()
        if version != 1:
            return seed.stem
        skip_blob()
        skip_blob()
        shared_count = u32()
        for _ in range(shared_count):
            take(8)
            skip_blob()
        interrupt_count = u32()
        for _ in range(interrupt_count):
            take(24)
        name = read_string().strip()
        return name or seed.stem
    except Exception:
        return seed.stem


def seed_category(seed: Path, seed_name: str | None = None) -> str:
    name = (seed_name or seed.stem).strip() or seed.stem
    parts = name.split("-")
    if len(parts) >= 2:
        return f"{parts[0]}-{parts[1]}"
    return parts[0] if parts else seed.stem


def make_sfuz_seed(output: Path, core0_hex: str, name: str, tags: Iterable[str] = ()) -> None:
    output.parent.mkdir(parents=True, exist_ok=True)
    command = [
        "python3",
        str(SFUZZ_HOME / "scripts" / "make_sfuz_seed.py"),
        "--output",
        str(output),
        "--core0-hex",
        core0_hex,
        "--name",
        name,
        "--description",
        f"generated by LinkNan runner for {name}",
    ]
    for tag in tags:
        command.extend(["--tag", tag])
    subprocess.run(command, check=True)


def collect_seed_paths(
    seed_args: list[str],
    seed_list: Path | None,
    seed_dir: Path | None,
    work_dir: Path,
    limit: int = 0,
    generate_smoke: bool = True,
    smoke_name: str = "vcs-smoke",
) -> list[Path]:
    seeds: list[Path] = []
    for item in seed_args:
        seeds.append(Path(item).expanduser())

    if seed_list:
        base = seed_list.expanduser().resolve().parent
        for raw_line in seed_list.expanduser().read_text(encoding="utf-8").splitlines():
            line = raw_line.split("#", 1)[0].strip()
            if not line:
                continue
            seed = Path(line).expanduser()
            seeds.append(seed if seed.is_absolute() else base / seed)

    if seed_dir:
        seed_dir = seed_dir.expanduser()
        require_dir(seed_dir)
        seeds.extend(sorted(seed_dir.glob("*.sfuz")))

    if not seeds and generate_smoke:
        generated = work_dir / "seeds" / "smoke.sfuz"
        make_sfuz_seed(generated, DEFAULT_SMOKE_HEX, smoke_name, tags=["generated", "smoke"])
        seeds.append(generated)

    resolved: list[Path] = []
    seen: set[Path] = set()
    for seed in seeds:
        path = seed.resolve()
        require_file(path)
        if path not in seen:
            resolved.append(path)
            seen.add(path)
    return resolved[:limit] if limit > 0 else resolved


def seed_from_raw_hex(raw_hex: str, work_dir: Path, case_name: str) -> tuple[Path, bytes]:
    raw = parse_hex_blob(raw_hex)
    raw_path = work_dir / "raw_payload.bin"
    raw_path.parent.mkdir(parents=True, exist_ok=True)
    raw_path.write_bytes(raw)
    seed = work_dir / "seed.sfuz"
    make_sfuz_seed(seed, raw_hex, case_name, tags=["rfuzz", "linknan-vcs"])
    return seed, raw
